pipeline {
    agent any
    environment {
        APP_Test_URL = "http://127.0.0.1:4723"
    }
    stages {
        stage('Checkout Code From Git') {
            steps {
                git branch: 'main', url: 'https://github.com/Wisanukorn-Test/test-ttb.git'
            }
        }
        
        stage('Run Test Automate') {
            steps {
                // รันสคริปต์ทดสอบอัตโนมัติ 
                bat 'robot --output Q2/output.xml Q2/TestCase.robot'
                bat 'robot --output Q3/output.xml Q3/APITest.robot'
                bat 'robot --output Q4/output.xml Q4/Minimal_Todo.robot'
            }
        }

        stage('Send Result To Jenkins') {
            steps {
                script {
                    // ตรวจสอบว่าไฟล์ output.xml ถูกสร้างหรือไม่
                    echo 'Checking if output.xml is created in Q2'
                    bat 'if exist Q2\\output.xml (echo File exists) else (echo File does not exist)'

                    echo 'Checking if output.xml is created in Q3'
                    bat 'if exist Q3\\output.xml (echo File exists) else (echo File does not exist)'

                    echo 'Checking if output.xml is created in Q4'
                    bat 'if exist Q4\\output.xml (echo File exists) else (echo File does not exist)'
                }
                junit '**/output.xml'  // ส่งผลลัพธ์การทดสอบไปยัง Jenkins
            }
        }
    }
}
