pipeline {
    agent any
    environment {
            APP_Test_URL = "http://127.0.0.1:4723"
    }
    stages {
        stage('Checkout Code From Git') {
            steps {
                git 'https://github.com/Wisanukorn-Test/test-ttb.git'
            }
        }
        
        stage('Run Test Automate') {
            steps {
                // รันสคริปต์ทดสอบอัตโนมัติ 
                bat 'robot ../Q2/TestCase.robot'
                bat 'robot ../Q3/APITest.robot'
                bat 'robot ../Q4/Minimal_Todo.robot'
            }
        }

        stage('Send Result To Jenkins') {
            steps {
                junit '**/output.xml'  // ส่งผลลัพธ์การทดสอบไปยัง Jenkins
            }
        }
    }
}
